### ISSUE TITLE
win下未获取到进程

### ISSUE THREAD

**Issue by ihacku** [ysrc/yulong-hids#12]
![image](https://user-images.githubusercontent.com/2731416/38489575-62118518-3c19-11e8-9057-7592cbb31499.png)

![image](https://user-images.githubusercontent.com/2731416/38489588-6f84dc72-3c19-11e8-8f0a-00963b1b07de.png)

实际驱动未能加载，可能与系统不兼容sha256签名的驱动有关。

待dual sign出一个包含sha1签名的驱动再试下。

**Comment by neargle** [comment]
系统版本是什么?

**Comment by ihacku** [comment]
fixed with https://github.com/ysrc/yulong-hids/commit/f7b5a0b139618f6a2618d7cdd078e4c69b369a42
