### ISSUE TITLE
server启动报错

### ISSUE THREAD

**Issue by djhighman** [ysrc/yulong-hids#13]
centos7.2.15系统，web正常配置启动之后。启动./server -db mongodbIP:27017 -es elasticIP:9200 报错：                                                                                                                                                2018/04/09 17:33:19 Get Config
2018/04/09 17:33:19 {false false {[] [] [] []} {[] [] [] []}   {false   } {false  false}}
2018/04/09 17:33:19 Start Task Thread
2018/04/09 17:33:19 cert error!

**Comment by neargle** [comment]
证书错误了 配置也没拉下来 而且报错的类型比较早期
建议：

- mongodb连不上，拉不下来配置，请检查一下mongodb
- 版本好像相对比较老了好像，可以换一个新的release

**Comment by djhighman** [comment]
1.mongodb可以连接上，查看mongodb的表，web已经把配置写入了。2.下载版本是yulong-0.4.2的，还有更新的吗？

**Comment by djhighman** [comment]
找到问题原因了，程序里面是获取mongo的agent数据库，配置文件里面配的yulong，所以获取不到对应的配置信息数据。

**Comment by neargle** [comment]
是的 数据库名不可以更改

**Comment by dundun99** [comment]
我也遇到类似问题 server启动报错：
2018/04/11 16:07:53 Start Task Thread
2018/04/11 16:07:53 Start Scan Thread
2018/04/11 16:07:53 Start Health Check Thread
2018/04/11 16:07:53 Start heartbeat thread
2018/04/11 16:07:53 cert error!
前述问题是怎么修改解决的呢？

**Comment by neargle** [comment]
@dundun99 看一下讨论记录啊

**Comment by dundun99** [comment]
web正常启动无报错，在mongo里写入的是agent库。mongo和es可以正常连接。前述说的配置文件里配的库名不一致 配置文件是指哪个文件？
