### ISSUE TITLE
mac的编译方式呢。。。。。

### ISSUE THREAD

**Issue by lucyzzz** [ysrc/yulong-hids#2]
mac的编译方式呢。。。。。

**Comment by ihacku** [comment]
不支持mac哦，虽然mac有服务器版本，但是很少人用哎，所以我们也没有覆盖。
如果你是编译了看看的话，得找win或者linux的机器了。

**Comment by neargle** [comment]
mac下部分模块可以使用交叉编译，但是agent的交叉编译是比较难实现的。
还是请到固定的系统环境下编译所需的agent吧。
