### ISSUE TITLE
服务端响应格式错误，请检查输入是否合理

### ISSUE THREAD

**Issue by bubaiwantong** [ysrc/yulong-hids#26]
下午在群里提问，大佬说我配置文件有问题，以下就修改完之后的配置文件

[mongodb]
url = "${IDS_MONGODB_URL||mongodb://192.168.25.71:27017/agent}"

[elastic_search]
url = "${IDS_ELASTICSEARCH_URL||http://192.168.25.71:9200/}"

配置完之后重启web，还是显示响应格式错误

![image](https://user-images.githubusercontent.com/33851803/38853601-669203d2-4250-11e8-914f-d8c63345e917.png)

**Comment by neargle** [comment]
应该修改为:

```
[mongodb]
url = mongodb://192.168.25.71:27017/agent

[elastic_search]
url = mongodb://192.168.25.71:27017/agent
```

配置文件目前暂时不支持读取环境变量

**Comment by bubaiwantong** [comment]
改成这样还是报错的，但是我改成如下：
[mongodb]
url = "${IDS_MONGODB_URL||mongodb://192.168.25.71:27017/agent}"

[elastic_search]
baseurl = "${IDS_ELASTICSEARCH_URL||http://192.168.25.71:9200/}"

他就好了，我是在无解。。。。。。。。现在不报错了

**Comment by neargle** [comment]
哦哦 之前yan师傅帮我做了这个更改 我忘记看commit了 现在才发现 你只是单纯的配置项写错了而已 base_url 才是
