### ISSUE TITLE
观察模式如何关闭，不关闭的话告警去哪里查看

### ISSUE THREAD

**Issue by bubaiwantong** [ysrc/yulong-hids#27]
如题，测试的话想手工制造一些触发策略的告警，然后看看是否会被记录

**Comment by ihacku** [comment]
![image](https://user-images.githubusercontent.com/2731416/38860093-f6f1c6f4-4261-11e8-9098-4e32ddb6137d.png)

**Comment by bubaiwantong** [comment]
谢谢
