### ISSUE TITLE
cert error

### ISSUE THREAD

**Issue by walrbug** [ysrc/yulong-hids#33]
[root@192 yulong]#  ./server -db 192.168.136.134:27017 -es 0.0.0.0:9200
2018/05/03 17:17:03 Get Config
2018/05/03 17:17:03 {false false {[] [] [] []} {[] [] [] []}   {false   } {false  false}}
2018/05/03 17:17:03 cert error!

**Comment by neargle** [comment]
web没有初始化吧 配置都没拉下来

**Comment by neargle** [comment]
去初始化一下数据库 在web的向导里
