### ISSUE TITLE
Win 32位 agnet 编译出错

### ISSUE THREAD

**Issue by hanjian007** [ysrc/yulong-hids#47]
C:\Go\src>go build -o yulong-hids\bin\win-32\agent.exe --ldflags="-w -s" yulong
hids\agent\agent.go
# yulong-hids/agent/vendor/github.com/akrennmair/gopcap
In file included from C:/WpdPack/Include/pcap/pcap.h:54:0,
                 from C:/WpdPack/Include/pcap.h:45,
                 from yulong-hids\agent\vendor\github.com\akrennmair\gopcap\pca
.go:12:
c:\mingw\include\stdio.h:345:12: error: expected '=', ',', ';', 'asm' or '__att
ibute__' before '__mingw__snprintf'
 extern int __mingw_stdio_redirect__(snprintf)(char*, size_t, const char*, ...)

            ^
c:\mingw\include\stdio.h:349:12: error: expected '=', ',', ';', 'asm' or '__att
ibute__' before '__mingw__vsnprintf'
 extern int __mingw_stdio_redirect__(vsnprintf)(char*, size_t, const char*, __V
LIST);
            ^

C:\Go\src>

**Comment by neargle** [comment]
gcc 的问题 应该 写一个c程序编译一下试看看就知道啦
看一下gcc的版本
