### ISSUE TITLE
No server node available

### ISSUE THREAD

**Issue by onesecurity** [ysrc/yulong-hids#48]
[root@yulong-hids]# ./agent 17.**.***.*8 debug
2018/06/28 11:13:29 DEBUG MODE
2018/06/28 11:13:29 Web API: https://17.**.***.*8/json/serverlist
2018/06/28 11:13:29 Available server node: []
2018/06/28 11:13:59 No server node available
panic: 1

goroutine 1 [running]:
yulong-hids/agent/client.(*Agent).init(0xc4200dc370)
	/usr/local/go/src/yulong-hids/agent/client/agent.go:61 +0x6cc
yulong-hids/agent/client.(*Agent).Run(0xc4200dc370)
	/usr/local/go/src/yulong-hids/agent/client/agent.go:82 +0x2b
main.main()
	/usr/local/go/src/yulong-hids/agent/agent.go:22 +0xb9

**Comment by yeahx** [comment]
这个需要自己确认 server 是否跑起来了，跑起来是否工作正常吧？

**Comment by ihacku** [comment]
先看下server起来没有
