### ISSUE TITLE
主机列表为空，agent运行正常

### ISSUE THREAD

**Issue by b2scrip** [ysrc/yulong-hids#51]
是需要开放那个端口和IP吗， SERVER 主动连接，还是AGENT 上报

我的主机列表没有数据
![agentlist](https://user-images.githubusercontent.com/28941864/43178674-21a296de-9001-11e8-84f8-11c2c1ad1078.png)

`
2018/07/25 11:42:54 Download dependent environment package
2018/07/25 11:42:55 Download Agent
2018/07/25 11:42:56 Agent file MD5: 087c9064c2040b5c74642d4c79e7f94f
2018/07/25 11:42:56 Agent download finished, hash check passed
2018/07/25 11:42:56 Copy the daemon to the installation directory
2018/07/25 11:42:56 Start the service
2018/07/25 11:42:56 Start service successfully
2018/07/25 11:42:56 Installed!
`

**Comment by PualCN** [comment]
你看看主机上面的server进程启动了没有
`./server -db 10.0.0.0:27017 -es 127.0.0.1:9200`

**Comment by neargle** [comment]
看看是不是有agent进程，否则用 debug 模式启动一下。
