### ISSUE TITLE
daemon common.go文件导入包重复

### ISSUE THREAD

**Issue by traceur** [ysrc/yulong-hids#59]
import (
	"crypto/tls"
	"net/http"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"sync"
	"time"
	"net"
	"strings"
	"fmt"

	"github.com/axgle/mahonia"
	"github.com/kardianos/service"
)

两个strings，编译会出错

**Comment by neargle** [comment]
Thx！修复并测试通过。
