### ISSUE TITLE
web引导步骤生成证书报错

### ISSUE THREAD

**Issue by ihacku** [ysrc/yulong-hids#6]
linux
![image](https://user-images.githubusercontent.com/2731416/38201150-c4bbf45a-36c9-11e8-85f1-8c3de8a25748.png)

要了下错误日志
![image](https://user-images.githubusercontent.com/2731416/38201128-a3d879c0-36c9-11e8-9a8b-08a712a64436.png)

**Comment by neargle** [comment]
这个错误并不是由web代码的日志爆出来的，暂时不能判断问题出在哪里。

**Comment by 449038001** [comment]
会不会是上一步上传的时候出的错误

**Comment by neargle** [comment]
问题已经解决，第三步上传的应该是包含着daemon，agent，data的zip包，不是data包。包的格式可以参见release，并可以用 build.py 生成。问题的作者上传错了。

**Comment by Eric96** [comment]
少传了Linux的包后面想加上去怎么办？
