### ISSUE TITLE
Error compile web binary

### ISSUE THREAD

**Issue by Aoshee** [ysrc/yulong-hids#60]
Hello,
I compile succes, but execute is error:

`./web flag redefined: graceful
panic: ./web flag redefined: graceful

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420068120, 0xae4860, 0xdf1c91, 0xa6e982, 0x8, 0xa7ff73, 0x21)
	/usr/local/go/src/flag/flag.go:810 +0x540
flag.BoolVar(0xdf1c91, 0xa6e982, 0x8, 0xc420190200, 0xa7ff73, 0x21)
	/usr/local/go/src/flag/flag.go:589 +0x72
github.com/astaxie/beego/grace.init.0()
	/home/exam/src/github.com/astaxie/beego/grace/grace.go:93 +0x60`

**Comment by neargle** [comment]
Which version of `beego` in your system?

**Comment by Aoshee** [comment]
Yep. How to fix error??

**Comment by neargle** [comment]
Print working directory of yulong. Is that in {gopath}/src?

**Comment by neargle** [comment]
Look https://stackoverflow.com/questions/41319633/vendor-folder-not-used-with-go-build
