### ISSUE TITLE
启动web.exe无法绑定ip地址

### ISSUE THREAD

**Issue by wangx666** [ysrc/yulong-hids#70]
操作环境windows server 2012
ES：5.6.10
在启动web.exe之后无法绑定ip地址

logs.log日志如下：
2019/04/22 11:03:25 [I] [asm_amd64.s:2361] https server Running on https://:443
2019/04/22 11:03:25 [I] [asm_amd64.s:2361] http server Running on http://:8088

**Comment by melooooooo** [comment]
你好，请问一下这个是什么原因呢，谢谢！
